{{- if .Values.ambient.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ambient2mqtt.fullname" . }}
  labels:
    {{- include "ambient2mqtt.labels" . | nindent 4 }}
type: Opaque
stringData:
  AMBIENT_USERNAME: {{ required "ambient.username is required when ambient.create is true" .Values.ambient.username | quote }}
  AMBIENT_PASSWORD: {{ required "ambient.password is required when ambient.create is true" .Values.ambient.password | quote }}
{{- end }}
